// Product Data
export interface Product {
    name: string;
    desc: string;
    price: number;
    oldPrice?: number;
    emoji: string;
    tag?: string;
    vip?: boolean;
    imgSrc?: string;
}

export const MENU: { [key: string]: Product[] } = {
    special: [
        { name: "Dear Box 16 Pcs", desc: "4 Pcs Crazy Shrimp Roll, 4 Pcs Seared Salmon Roll, 4 Pcs Oman Chips Roll & 4 Pcs California Roll", price: 89, oldPrice: 120, emoji: "🍣", tag: "Popular", imgSrc: "/images/31.png" },
        { name: "Happy Box 16 Pcs", desc: "4 Pcs Eel Dragon Roll, 4 Pcs Spicy Tuna Dragon Roll, 4 Pcs Arigato Roll & 4 Pcs Salmon Nigiri", price: 99, oldPrice: 130, emoji: "🍱", tag: "Hot Deal", imgSrc: "/images/32.png" },
        { name: "Mini Salmon Lover 12 Pcs", desc: "4 Pcs Salmon Nigiri, 4 Pcs Salmon Sashimi & 4 Pcs Salmon Hoso Maki", price: 99, emoji: "🐟", tag: "Value", imgSrc: "/images/33.png" },
        { name: "Tuna Maki 8 Pcs", desc: "Classic tuna hosomaki roll", price: 39, emoji: "🍣", imgSrc: "/images/special-01.png" },
        { name: "Salmon Avocado Roll 8 Pcs", desc: "Inside-out roll with salmon & avocado", price: 49, emoji: "🍣", imgSrc: "/images/special-02.png" },
        { name: "Mango Veggie Roll 8 Pcs", desc: "Avocado, lettuce & mango topped with sesame", price: 39, emoji: "🥑", tag: "Vegan", imgSrc: "/images/special-03.png" },
        { name: "Party Platter 64 Pcs", desc: "Chef’s choice of mixed classic & signature rolls", price: 259, emoji: "🍱", tag: "Sharing", imgSrc: "/images/special-04.png" },
        { name: "California Salmon Roll 8 Pcs", desc: "California style roll with salmon & crab", price: 49, emoji: "🍣", imgSrc: "/images/special-05.png" },
        { name: "Rainbow Dream Roll 8 Pcs", desc: "Layered salmon, tuna & avocado over California roll", price: 59, emoji: "🌈", tag: "Chef Special", imgSrc: "/images/special-06.png" },
        { name: "Mango Dragon Roll 8 Pcs", desc: "Crispy shrimp, mango & avocado with spicy mayo", price: 59, emoji: "🐉", imgSrc: "/images/special-07.png" },
        { name: "Flaming Shrimp Roll 8 Pcs", desc: "Seared shrimp roll with spicy mayo drizzle", price: 59, emoji: "🔥", imgSrc: "/images/special-08.png" },
        { name: "Green Dragon Roll 8 Pcs", desc: "Tempura prawn roll topped with avocado & chili", price: 59, emoji: "🐉", imgSrc: "/images/special-09.png" },
        { name: "Crispy Tobiko Roll 8 Pcs", desc: "Crab & avocado roll topped with tobiko & mayo", price: 59, emoji: "🍣", imgSrc: "/images/special-10.png" },
        { name: "Crunchy Volcano Roll 8 Pcs", desc: "Crispy coated roll with salmon & avocado", price: 59, emoji: "🌋", tag: "Spicy", imgSrc: "/images/special-11.png" },
        { name: "Mixed Sushi Taster 18 Pcs", desc: "Selection of maki, nigiri & sashimi from the chef", price: 179, emoji: "🍣", imgSrc: "/images/34.png" },
    ],
    lovers: [
        { name: "Dear Box 16 Pcs", desc: "4 Pcs Crazy Shrimp Roll, 4 Pcs Seared Salmon Roll, 4 Pcs Oman Chips Roll & 4 Pcs California Roll", price: 89, emoji: "🍣", imgSrc: "/images/31.png" },
        { name: "Happy Box 16 Pcs", desc: "4 Pcs Eel Dragon Roll, 4 Pcs Spicy Tuna Dragon Roll, 4 Pcs Arigato Roll & 4 Pcs Salmon Nigiri", price: 99, emoji: "🍣", imgSrc: "/images/32.png" },
        { name: "Mini Salmon Lover 12 Pcs", desc: "4 Pcs Salmon Nigiri, 4 Pcs Salmon Sashimi & 4 Pcs Salmon Hoso Maki", price: 99, emoji: "🐟", imgSrc: "/images/33.png" },
        { name: "Raw Mixed Platter 24 Pcs", desc: "8 Pcs New Phila Roll, 4 Pcs Tiger Phila Roll, 4 Pcs California Salmon Dream Roll, 4 Pcs Salmon Nigiri, 2 Pcs Tuna Nigiri & 2 Pcs Ebi Nigiri", price: 139, emoji: "🍱", imgSrc: "/images/34.png" },
        { name: "Super Salmon Lover Box 24 Pcs", desc: "4 Pcs Philadelphia Roll, 4 Pcs Salmon Nigiri, 4 Pcs Volcano Roll, 4 Pcs Flaming Star Salmon Roll, 4 Pcs Cooked Salmon Roll & 4 Pcs Spring Salmon Roll", price: 149, emoji: "🍣", imgSrc: "/images/35.png" },
        { name: "Shrimp Lover Box 24 Pcs", desc: "8 Pcs King Salmon Shrimp Roll, 8 Pcs Crazy Shrimp Roll & 8 Pcs Shrimp Hoso Maki", price: 129, emoji: "🦐", imgSrc: "/images/36.png" },
        { name: "Crab Lover Box 28 Pcs", desc: "4 Pcs California Roll, 4 Pcs Black Cali Roll, 4 Pcs Arigato Roll, 4 Pcs Crunchy Crab Roll, 4 Pcs Kani Nigiri & 8 Pcs Kanikama Hosomaki", price: 149, emoji: "🦀", imgSrc: "/images/37.png" },
        { name: "Vibrant Vegetable Box 28 Pcs", desc: "8 Pcs Yasai Roll, 8 Pcs Veg Futo Roll, 8 Pcs Avocado Maki & 4 Pcs Beetroot Roll", price: 99, emoji: "🥑", tag: "Vegan", imgSrc: "/images/38.png" },
        { name: "Matsu Sashimi & Nigiri 18 Pcs", desc: "3 Pcs Salmon Sashimi, 3 Pcs Salmon Belly Sashimi, 3 Pcs Tuna Sashimi, 3 Pcs Salmon Nigiri, 3 Pcs Ebi Nigiri & 3 Pcs Kani Nigiri", price: 189, emoji: "🍱", imgSrc: "/images/39.png" },
        { name: "Royal Salmon Lover Box 32 Pcs", desc: "8 Pcs Salmon Nigiri, 8 Pcs Salmon Philadelphia Roll, 4 Pcs Salmon Belly Nigiri, 4 Pcs Salmon Volcano Roll, 4 Pcs Cooked Salmon Roll & 4 Pcs Salmon Nisoku", price: 199, emoji: "🍣", imgSrc: "/images/40.png" },
    ],
    sakura: [
        { name: "Wow Classico Box A 20 Pcs", desc: "4 Pcs Salmon Dream Roll, 4 Pcs Shrimp Dynamite Roll, 4 Pcs Crazy Crab Roll, 4 Pcs Crab Philly Roll & 4 Pcs Salmo Hoso Maki", price: 109, emoji: "🌸", imgSrc: "/images/24.png" },
        { name: "Wow Classico Box B 12 Pcs", desc: "4 Pcs Seared Salmon Roll, 4 Pcs Spicy Seared Salmon Roll & 4 Pcs Golden Garden Roll", price: 79, emoji: "🍣", imgSrc: "/images/25.png" },
        { name: "Wow Classico Box C 12 Pcs", desc: "4 Pcs Dragon Roll, 4 Pcs Crab Philly Roll & 4 Pcs Kanikama Hoso Maki", price: 69, emoji: "🍱", imgSrc: "/images/26.png" },
        { name: "Philla Dream Box 24 Pcs", desc: "8 Pcs Philadelphia Salmon Roll, 8 Pcs Crab Philly Roll, 4 Pcs Tiger Phila Roll & 4 Pcs Unagi Salmon Cream Salmon", price: 179, emoji: "🌸", imgSrc: "/images/27.png" },
    ],
    cooked: [
        { name: "Fire & Sea Box A 16 Pcs", desc: "4 Pcs Eel Dragon Roll, 4 Pcs Dragon Roll, 4 Pcs Crazy Shrimp & 4 Pcs Veg Creamy Roll", price: 99, emoji: "🔥", imgSrc: "/images/12.png" },
        { name: "Fire & Sea Box B 24 Pcs", desc: "8 Pcs Dynamite Roll, 4 Pcs Seared Salmon Roll, 4 Pcs Crazy Crab Roll, 4 Pcs Cooked Salmon Roll & 4 Pcs Dragon Roll", price: 149, emoji: "🔥", imgSrc: "/images/13.png" },
        { name: "Cooked Box 20 Pcs", desc: "4 Pcs Dragon Roll, 4 Pcs Dynamite Shrimp Roll, 4 Pcs Oman Crispy Roll, 4 Pcs Crazy Crab Roll & 4 Pcs Crab Dragon Roll", price: 129, emoji: "🍱", imgSrc: "/images/14.png" },
        { name: "Fire & Sea Box C 32 Pcs", desc: "4 Pcs Cooked Salmon Nigiri, 4 Pcs Mango Crab Roll, 4 Pcs Eel Dragon Roll, 4 Pcs Rosie Roll, 4 Pcs Cooked Salmon Roll, 4 Pcs Arigato Roll, 4 Pcs Cooked Futo Roll & 4 Pcs Crazy Shrimp Roll", price: 219, emoji: "🔥", tag: "Best Value", imgSrc: "/images/15.png" },
    ],
    vip: [
        { name: "Fusion VIP Moriwase 24 Pcs", desc: "4 Pcs Unagi Dragon Roll, 4 Pcs Salmon Philadelphia Roll, 4 Pcs Crazy Crab Roll, 4 Pcs Cooked Salmon Roll, 4 Pcs Salmon Sashimi, 2 Pcs Tuna Nigiri & 2 Pcs Ebi Nigiri", price: 149, emoji: "👑", tag: "VIP", imgSrc: "/images/16.png" },
        { name: "Fusion VIP Moriwase 32 Pcs", desc: "4 Pcs Salmon Nigiri, 4 Pcs Salmon Philadelphia Roll, 4 Pcs Mango Crab Roll, 4 Pcs Crazy Shrimp Roll, 4 Pcs Rosie Roll, 4 Pcs Unagi Dragon Roll, 4 Pcs Yasai Roll & 4 Pcs Tuna Maki", price: 199, emoji: "👑", tag: "VIP", imgSrc: "/images/17.png" },
        { name: "Fusion VIP Moriwase 60 Pcs", desc: "8 Pcs Unagi Dragon Roll, 8 Pcs Salmon Philadelphia Roll, 8 Pcs Crazy Shrimp Roll, 8 Pcs Crazy Crab Roll, 4 Pcs Dragon Roll, 4 Pcs California Roll, 4 Pcs Oman Crunchy Roll, 4 Pcs Avocado Hosomaki, 3 Pcs Salmon Sashimi, 3 Pcs Tuna Sashimi, 3 Pcs Salmon Nigiri & 3 Pcs Tuna Nigiri", price: 369, emoji: "🏆", tag: "Premium", imgSrc: "/images/18.png" },
    ],
    maki: [
        { name: "Sake Maki", desc: "Classic salmon hoso maki roll", price: 29, emoji: "🍣", imgSrc: "/images/41.png" },
        { name: "Tuna Maki", desc: "Fresh tuna hoso maki roll", price: 29, emoji: "🍱", imgSrc: "/images/42.png" },
        { name: "Kappa Maki", desc: "Crisp cucumber hoso maki roll", price: 19, emoji: "🥒", tag: "Vegan", imgSrc: "/images/43.png" },
        { name: "Mango Maki", desc: "Sweet mango hoso maki roll", price: 19, emoji: "🥭", tag: "Vegan", imgSrc: "/images/44.png" },
        { name: "Kanikama Maki", desc: "Crab stick hoso maki roll", price: 19, emoji: "🦀", imgSrc: "/images/45.png" },
        { name: "Unagi Maki", desc: "Grilled eel hoso maki roll", price: 29, emoji: "🐍", imgSrc: "/images/46.png" },
    ],
    temaki: [
        { name: "Sake Temaki", desc: "Fresh salmon hand roll in a crispy nori cone", price: 39, emoji: "🥢", imgSrc: "/images/19.png" },
        { name: "California Temaki", desc: "Crab, avocado & cucumber hand roll", price: 29, emoji: "🥢", imgSrc: "/images/20.png" },
        { name: "Unagi Temaki", desc: "Grilled eel hand roll with sweet sauce", price: 39, emoji: "🥢", imgSrc: "/images/8.png" },
        { name: "Shrimp Avocado Temaki", desc: "Shrimp & creamy avocado hand roll", price: 39, emoji: "🥢", imgSrc: "/images/47.png" },
    ],
    sashimi: [
        { name: "Salmon Sashimi 5 Pcs", desc: "Slices of fresh salmon sashimi", price: 49, emoji: "🐟", imgSrc: "/images/33.png" },
        { name: "Tuna Sashimi 5 Pcs", desc: "Slices of premium tuna sashimi", price: 49, emoji: "🐟", imgSrc: "/images/39.png" },
        { name: "Sashimi Moriwase 18 Pcs", desc: "Chef selection of mixed sashimi", price: 179, emoji: "🍣", imgSrc: "/images/34.png" },
    ],
    nigiri: [
        { name: "Kani Nigiri 5 Pcs", desc: "Hand-formed sushi with crab stick", price: 49, emoji: "🦀", imgSrc: "/images/menu-nigiri.png" },
        { name: "Ebi Nigiri 5 Pcs", desc: "Hand-formed sushi with cooked shrimp", price: 49, emoji: "🦐", imgSrc: "/images/menu-nigiri.png" },
        { name: "Spicy Seared Salmon Nigiri 5 Pcs", desc: "Lightly seared salmon with spicy sauce", price: 59, emoji: "🐟", tag: "Spicy", imgSrc: "/images/menu-nigiri.png" },
        { name: "Avocado Nigiri 4 Pcs", desc: "Fresh avocado on seasoned rice", price: 29, emoji: "🥑", tag: "Vegan", imgSrc: "/images/menu-nigiri.png" },
        { name: "Avo Tempura Nigiri 4 Pcs", desc: "Tempura-fried avocado on rice", price: 29, emoji: "🥑", imgSrc: "/images/menu-nigiri.png" },
        { name: "Flame & Creamy Nigiri Set 8 Pcs", desc: "Salmon & avocado nigiri with roe", price: 69, emoji: "🍣", imgSrc: "/images/menu-nigiri.png" },
        { name: "Smoked Teriyaki Nigiri Set 8 Pcs", desc: "Smoked teriyaki fish nigiri", price: 99, emoji: "🍣", imgSrc: "/images/88.png" },
        { name: "Super Nigiri 16 Pcs", desc: "4 Pcs Salmon, 4 Pcs Salmon Belly, 4 Pcs Tuna & 4 Pcs Ebi Nigiri", price: 119, emoji: "🍣", tag: "Best Value", imgSrc: "/images/90.png" },
    ],
    starters: [
        { name: "Calamari Fried", desc: "Golden fried calamari rings with lemon", price: 59, emoji: "🦑", imgSrc: "/images/131.png" },
        { name: "Chicken Katsu", desc: "Crispy breaded chicken cutlets with cabbage salad & dipping sauce", price: 69, emoji: "🍗", imgSrc: "/images/132.png" },
        { name: "Karage Fried", desc: "Japanese fried chicken pieces with chili", price: 39, emoji: "🍗", imgSrc: "/images/130.png" },
        { name: "Shrimp Tempura", desc: "Light battered fried shrimp with garnish", price: 59, emoji: "🦐", imgSrc: "/images/127.png" },
        { name: "Dynamite Shrimp", desc: "Shrimp in creamy spicy sauce", price: 59, emoji: "🦐", tag: "Spicy", imgSrc: "/images/128.png" },
        { name: "Takoyaki Octopus Ball", desc: "Four octopus balls with sauce, mayo & bonito", price: 29, emoji: "🐙", imgSrc: "/images/126.png" },
        { name: "Salted Edamame", desc: "Steamed edamame pods lightly salted", price: 19, emoji: "🫛", imgSrc: "/images/124.png" },
        { name: "Spicy Edamame", desc: "Steamed edamame with spicy seasoning", price: 29, emoji: "🫛", tag: "Spicy", imgSrc: "/images/menu-starters.png" },
        { name: "Veg Gyoza", desc: "Pan-fried vegetable dumplings", price: 29, emoji: "🥟", tag: "Vegan", imgSrc: "/images/125.png" },
        { name: "Chicken Gyoza", desc: "Pan-fried chicken dumplings", price: 39, emoji: "🥟", imgSrc: "/images/125.png" },
        { name: "Shrimp Gyoza", desc: "Pan-fried shrimp dumplings", price: 49, emoji: "🥟", imgSrc: "/images/125.png" },
        { name: "Plain Miso Soup", desc: "Classic miso with tofu & seaweed", price: 19, emoji: "🍜", imgSrc: "/images/129.png" },
        { name: "Veg Miso Soup", desc: "Miso soup with vegetables", price: 29, emoji: "🍜", tag: "Vegan", imgSrc: "/images/menu-starters.png" },
        { name: "Chicken Miso Soup", desc: "Miso soup with chicken", price: 39, emoji: "🍜", imgSrc: "/images/menu-starters.png" },
        { name: "Shrimp Miso Soup", desc: "Miso soup with shrimp", price: 49, emoji: "🍜", imgSrc: "/images/menu-starters.png" },
    ],
    noodles: [
        { name: "Seafood Ramen", desc: "Ramen with shrimp, egg, corn, bean sprouts & nori", price: 69, emoji: "🍜", imgSrc: "/images/133.png" },
        { name: "Chicken Ramen", desc: "Ramen with grilled chicken, egg, narutomaki & nori", price: 59, emoji: "🍜", imgSrc: "/images/134.png" },
        { name: "Chicken Yakisoba", desc: "Stir-fried noodles with chicken & vegetables", price: 49, emoji: "🍜", imgSrc: "/images/135.png" },
        { name: "Seafood Yakisoba", desc: "Stir-fried noodles with shrimp & mixed vegetables", price: 59, emoji: "🍜", imgSrc: "/images/136.png" },
        { name: "Veg Yakisoba", desc: "Stir-fried noodles with mixed vegetables", price: 39, emoji: "🥢", tag: "Vegan", imgSrc: "/images/137.png" },
        { name: "Chicken Yaki Sanuki Udon", desc: "Thick udon stir-fried with chicken & greens", price: 49, emoji: "🍜", imgSrc: "/images/138.png" },
        { name: "Shrimp Yaki Sanuki Udon", desc: "Thick udon stir-fried with shrimp & vegetables", price: 59, emoji: "🍜", imgSrc: "/images/139.png" },
        { name: "Veg Yaki Sanuki Udon", desc: "Thick udon stir-fried with vegetables", price: 39, emoji: "🥢", tag: "Vegan", imgSrc: "/images/140.png" },
    ],
    beverages: [
        { name: "Water", desc: "Oasis still water", price: 2, emoji: "💧", imgSrc: "/images/141.png" },
        { name: "San Pellegrino Sparkling Water", desc: "Italian sparkling mineral water", price: 12, emoji: "🥤", imgSrc: "/images/143.png" },
        { name: "Red Bull", desc: "Energy drink", price: 13, emoji: "⚡", imgSrc: "/images/142.png" },
        { name: "Sprite", desc: "Lemon-lime soda", price: 7, emoji: "🥤", imgSrc: "/images/147.png" },
        { name: "Lipton Peach Ice Tea", desc: "Peach iced tea 320ml, low calorie", price: 9, emoji: "🍑", imgSrc: "/images/144.png" },
        { name: "Diet Pepsi", desc: "Diet cola", price: 7, emoji: "🥤", imgSrc: "/images/145.png" },
        { name: "Pepsi", desc: "Classic Pepsi", price: 7, emoji: "🥤", imgSrc: "/images/146.png" },
        { name: "Mountain Dew", desc: "Citrus soda", price: 7, emoji: "🥤", imgSrc: "/images/148.png" },
        { name: "Mirinda Orange", desc: "Orange flavored soda", price: 7, emoji: "🍊", imgSrc: "/images/149.png" },
    ],
    poke: [
        { name: "Fusion Rainbow Salmon Fish Poke Bowl", desc: "Japanese rice, salmon, mango, avocado, shredded crab, cabbage, lettuce, edamame, black & orange tobiko. Served with ponzu.", price: 89, emoji: "🐟", tag: "Popular", imgSrc: "/images/110.png" },
        { name: "Healthy Salmon Avocado Pokebowl", desc: "Japanese rice, avocado, orange tobiko, kizami nori, sesame. Served with ponzu.", price: 89, emoji: "🥑", imgSrc: "/images/111.png" },
        { name: "Veg Poke Bowl", desc: "Japanese rice, cucumber, avocado, mango, edamame, beetroot tanuki, sesame. Served with ponzu.", price: 49, emoji: "🥗", tag: "Vegan", imgSrc: "/images/112.png" },
        { name: "California Heaven Poke Bowl", desc: "Japanese rice, avocado, mango, cucumber, red cabbage, lettuce, shredded crab, orange tobiko, edamame. Served with ponzu.", price: 69, emoji: "🌊", imgSrc: "/images/113.png" },
    ],
    salad: [
        { name: "Avocado & Egg Power Salad", desc: "Lettuce, avocado, cherry tomatoes & hard-boiled eggs", price: 59, emoji: "🥗", imgSrc: "/images/120.png" },
        { name: "Crab Salad", desc: "Shredded crab with creamy dressing & tobiko", price: 59, emoji: "🦀", imgSrc: "/images/121.png" },
        { name: "Healthy Salmon Avo Goma Tare", desc: "Salmon, avocado & lettuce with goma tare & roe", price: 99, emoji: "🐟", imgSrc: "/images/122.png" },
        { name: "Mixed Seaweed Salad", desc: "Classic seaweed salad with sesame seeds", price: 59, emoji: "🥗", imgSrc: "/images/114.png" },
        { name: "Goma Fruity Salad", desc: "Mixed greens & fruit with sesame dressing", price: 59, emoji: "🥗", imgSrc: "/images/119.png" },
        { name: "Healthy Salmon Avocado Salad", desc: "Salmon, avocado, cabbage & carrots with crispy topping", price: 89, emoji: "🐟", imgSrc: "/images/123.png" },
        { name: "Salmon Carpaccio", desc: "Thinly sliced salmon with lemon & red onion", price: 69, emoji: "🐟", imgSrc: "/images/115.png" },
        { name: "Spicy Kissed Salmon Salad", desc: "Diced salmon with chili, edamame & mint", price: 89, emoji: "🌶️", tag: "Spicy", imgSrc: "/images/116.png" },
        { name: "Island Shrimp Salad", desc: "Shrimp, avocado, tomatoes & broccoli", price: 89, emoji: "🦐", imgSrc: "/images/117.png" },
        { name: "Spicy Crunchy Salmon Tartar", desc: "Salmon tartar with crunchy garnish & roe", price: 99, emoji: "🌶️", tag: "Spicy", imgSrc: "/images/118.png" },
    ],
    curry: [
        { name: "Chicken Katsu Curry Rice", desc: "Crispy chicken katsu with rice & Japanese curry", price: 49, emoji: "🍛", imgSrc: "/images/99.png" },
        { name: "Chicken Karage Curry Rice", desc: "Fried chicken karage with rice & curry", price: 49, emoji: "🍛", imgSrc: "/images/100.png" },
        { name: "Chicken Fried Rice", desc: "Wok-fried rice with chicken & green onions", price: 49, emoji: "🍚", imgSrc: "/images/102.png" },
        { name: "Garlic Fried Rice", desc: "Garlic-infused fried rice with green onions", price: 39, emoji: "🍚", imgSrc: "/images/menu-curry.png" },
        { name: "Seafood Fried Rice", desc: "Fried rice with mixed seafood", price: 59, emoji: "🦐", imgSrc: "/images/103.png" },
        { name: "Shrimp Fried Rice", desc: "Fried rice with plump shrimp", price: 59, emoji: "🦐", imgSrc: "/images/menu-curry.png" },
        { name: "Tori Teriyaki Bowl", desc: "Teriyaki chicken with rice & broccoli", price: 49, emoji: "🍱", imgSrc: "/images/108.png" },
        { name: "Grilled Salmon Teriyaki Bowl", desc: "Grilled salmon with rice & broccoli", price: 79, emoji: "🐟", imgSrc: "/images/109.png" },
        { name: "Grilled Unagi Bowl", desc: "Grilled eel with savory sauce & sesame", price: 99, emoji: "🐍", imgSrc: "/images/107.png" },
        { name: "Teriyaki Chicken", desc: "Glazed teriyaki chicken with fried rice", price: 79, emoji: "🍗", imgSrc: "/images/108.png" },
        { name: "Salmon Teriyaki", desc: "Grilled salmon teriyaki with fried rice", price: 89, emoji: "🐟", imgSrc: "/images/109.png" },
    ]
};

export const CATEGORIES = [
    { id: 'special', name: 'Special Offers', icon: '🌟' },
    { id: 'starters', name: 'Starters', icon: '🥟' },
    { id: 'lovers', name: 'Lovers Box', icon: '🍣' },
    { id: 'sakura', name: 'Sakura Combos', icon: '🌸' },
    { id: 'cooked', name: 'Cooked Box', icon: '🔥' },
    { id: 'vip', name: 'VIP Moriwase', icon: '👑' },
    { id: 'maki', name: 'Hoso Maki', icon: '🌿' },
    { id: 'temaki', name: 'Temaki', icon: '🥢' },
    { id: 'sashimi', name: 'Sashimi', icon: '🍣' },
    { id: 'nigiri', name: 'Nigiri', icon: '🍣' },
    { id: 'noodles', name: 'Noodles', icon: '🍜' },
    { id: 'curry', name: 'Curry & Fried Rice', icon: '🍛' },
    { id: 'poke', name: 'Poke Bowl', icon: '🐟' },
    { id: 'salad', name: 'Salad', icon: '🥗' },
    { id: 'beverages', name: 'Beverages', icon: '🥤' },
];
